name: PR Tests For express-oauth2-client

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set git info'
        run: |
          git config --global user.name benbarron
          git config --global user.email benbarron@protonmail.com
      - name: 'Checkout'
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Check package version
        run: |
          git fetch origin master:master
          PACK_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          MASTER_VERSION=$(git show master:package.json | cat | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          if ["$PACK_VERSION" == "$MASTER_VERSION"]; then
            echo "Version $PACK_VERSION wasn't updated"
            exit 1
          fi
      - run: npm ci
      - run: npm test
