name: PR Tests For express-oauth2-client

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set git info'
        run: |
          git config --global user.name benbarron
          git config --global user.email benbarron@protonmail.com
      - name: 'Checkout'
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
      - run: npm ci
      - run: npm test
